require:
  - rubocop-rails

AllCops:
 TargetRubyVersion: 3.0
 Exclude:
   - 'bin/**/*'
   - 'vendor/**/*'
   - 'db/**/*'
   - 'node_modules/**/*'
   - 'config/**/*'
   - 'script/**/*'
   - 'spec/rails_helper.rb'

Documentation:
 Enabled: false

Style/FrozenStringLiteralComment:
 Enabled: false

Metrics/BlockLength:
 IgnoredMethods: ['describe', 'context', 'feature', 'scenario', 'let']

Metrics/LineLength:
  Max: 80

AsciiComments:
  Enabled: false